services:
  ${MYSQL_SERVICE_NAME}:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - content_host_network
    restart: always
    expose:
      - "${MYSQL_PORT}"  # Открытие порта внутри Docker-сети

volumes:
  mysql_data:
    driver: local

networks:
  content_host_network:
    external: true
