#!/bin/bash


echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
echo "MYSQL_USER: $MYSQL_USER"
echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
echo "MYSQL_COMPOSE_NAME: $MYSQL_COMPOSE_NAME"
echo "MYSQL_CONTAINER_NAME: $MYSQL_CONTAINER_NAME"
echo "MYSQL_DATABASE_GALLERY: $MYSQL_DATABASE_GALLERY"


#
## Запуск контейнера MySQL
