name: Deploy MySQL Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy_mysql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml and init.sh to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./db/docker-compose.yml,./db/init.sh"
          target: "$HOME"

      - name: Debug environment variables
        run: |
          echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
          echo "MYSQL_USER: $MYSQL_USER"
          echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
          echo "MYSQL_COMPOSE_NAME: $MYSQL_COMPOSE_NAME"
          echo "MYSQL_CONTAINER_NAME: $MYSQL_CONTAINER_NAME"
          echo "MYSQL_DATABASE_GALLERY: $MYSQL_DATABASE_GALLERY"
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_COMPOSE_NAME: ${{ secrets.MYSQL_COMPOSE_NAME }}
          MYSQL_CONTAINER_NAME: ${{ secrets.MYSQL_CONTAINER_NAME }}
          MYSQL_DATABASE_GALLERY: ${{ secrets.MYSQL_DATABASE_GALLERY }}

      - name: Deploy MySQL (Run docker-compose and initialize)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/db
            chmod +x init.sh
            ./init.sh
        run: |
          echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
          echo "MYSQL_USER: $MYSQL_USER"
          echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
          echo "MYSQL_COMPOSE_NAME: $MYSQL_COMPOSE_NAME"
          echo "MYSQL_CONTAINER_NAME: $MYSQL_CONTAINER_NAME"
          echo "MYSQL_DATABASE_GALLERY: $MYSQL_DATABASE_GALLERY"
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_COMPOSE_NAME: ${{ secrets.MYSQL_COMPOSE_NAME }}
          MYSQL_CONTAINER_NAME: ${{ secrets.MYSQL_CONTAINER_NAME }}
          MYSQL_DATABASE_GALLERY: ${{ secrets.MYSQL_DATABASE_GALLERY }}
