name: Deploy Traefik

on:
  push:
    branches:
      - main  # или ваша целевая ветка для деплоя

jobs:
  deploy_traefik:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key and deploy Traefik
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: your-vps-domain.com
          username: user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/your/traefik
            ./deploy.sh
