name: Deploy Traefik Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy_traefik:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key and deploy Traefik
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: whoami
